name: Publish Docker image

on:
  push:
    branches:
      - "master"


jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: buildjet-2vcpu-ubuntu-2204-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "jimzdevops/utol"


      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: jimzdevops/asynqmon:${{ env.GITHUB_REF_SLUG }}
          # For pull requests, export results to the build cache.
          # Otherwise, push to a registry.
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry,push=true' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
